# Generated by Django 4.0.4 on 2022-08-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=700)),
                ('host_name', models.CharField(max_length=700)),
                ('os_name', models.CharField(max_length=700)),
                ('os_version', models.CharField(max_length=700)),
                ('os_manufacturer', models.CharField(max_length=700)),
                ('os_configuration', models.CharField(max_length=700)),
                ('os_build_type', models.CharField(max_length=700)),
                ('registered_owner', models.CharField(max_length=700)),
                ('registered_organization', models.CharField(max_length=700)),
                ('product_iD', models.CharField(max_length=700)),
                ('original_Install_Date', models.CharField(max_length=700)),
                ('system_Boot_Time', models.CharField(max_length=700)),
                ('system_Manufacturer', models.CharField(max_length=700)),
                ('system_Model', models.CharField(max_length=700)),
                ('system_Type', models.CharField(max_length=700)),
                ('processor', models.CharField(max_length=700)),
                ('bios_Version', models.CharField(max_length=700)),
                ('windows_Directory', models.CharField(max_length=700)),
                ('system_Directory', models.CharField(max_length=700)),
                ('system_Locale', models.CharField(max_length=700)),
                ('input_Locale', models.CharField(max_length=700)),
                ('time_Zone', models.CharField(max_length=700)),
                ('total_Physical_Memory', models.CharField(max_length=700)),
                ('available_Physical_Memory', models.CharField(max_length=700)),
                ('sender_id', models.CharField(max_length=700)),
                ('decrypted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
