# Generated by Django 4.0.4 on 2022-08-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_id',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
