# Generated by Django 4.0.4 on 2022-08-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_profile_sender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='How_To_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='#step 1', max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('rep', models.CharField(help_text='first', max_length=20, null=True, unique=True)),
                ('image', models.ImageField(default='avatar.png', null=True, upload_to='how_img/')),
            ],
        ),
    ]
